Repository cloud-native-toolkit/terraform-tools-artifactory, pull requests merged in 2020-12, with the labels that each got.

#28 Uses ibm-garage-cloud/action-module-verify action for verify logic
  .github/scripts/apply.sh
  .github/scripts/capture-cluster-state.sh
  .github/scripts/destroy.sh
  .github/scripts/validate-deploy.sh
  .github/scripts/validate-destroy.sh
  .github/scripts/waitForEndpoint.sh
  .github/workflows/verify.yaml
Labels: chore, patch

#29 Uses ibm-garage-cloud/action-module-catalog to build catalog metadata
  .github/workflows/publish-assets.yaml
Labels: chore, patch

#30 Adds step to generate DIST_DIR
  .github/workflows/publish-assets.yaml
Labels: chore, patch

#31 Removes unused workflow scripts
  .github/scripts/build-module-metadata.sh
  .github/scripts/merge-module-metadata.sh
  .github/workflows/publish-assets.yaml
  test/stages/stage1-namespaces.tf
  test/stages/variables.tf
Labels: chore, patch

#32 Adds repoSlug back to Build catalog step
  .github/workflows/publish-assets.yaml
Labels: bug, patch

#33 Removes repoSlug again
  .github/workflows/publish-assets.yaml
Labels: bug, chore

#34 Uses ibm-garage-cloud/action-repository-dispatch for notify workflow
  .github/workflows/notify.yaml
Labels: chore, patch

#35 Updates GITHUB_TOKEN value
  .github/workflows/notify.yaml
Labels: chore, patch

#36 fix storageClassName
  main.tf
  variables.tf
Labels: bug, minor
